language: node_js
node_js:
  - '4.0'
  - '4.1'
  - '4.2'

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo npm install -g gulp bower sequelize-cli groc
  - npm install
  - cd frontend && bower install

script:
  - gulp build
